fix: fix writing of failed filename to json results log file.
Fix writing of failed filename to json results log file by converting
Path object to str.

Before this patch, the follwoing exeception would be raised when failed
files needed to be serialized to json:

    TypeError: Object of type PosixPath is not JSON serializable